### ISSUE TITLE
Failed to open

### ISSUE THREAD

**Issue by SplitGemini** [quantum5/winscap#3]
Hi:
    Error message is: **Failed to open: ??? (Realtek High Definition Audio): Requested sound format unsupported.**, ??? means some Chinese characters that encoding is not supported .
    Bluetooth playback is normal, but general audio fails.

**Comment by quantum5** [comment]
Most likely you are using the wrong sampling rate. Certain devices default to 48 kHz and others default to 44.1 kHz, which makes it impossible to use one command line to capture both devices.

The solution is to change Windows audio settings for all your output devices so that they all use the same sampling rate, and pass that on the command line.

**Comment by SplitGemini** [comment]
It works, thanks a lot.
